// this list is a WIP
// i - instamine
// m - mineable
// n - not mineable
// p - premined
// s - significantly premined

var mineable = {
	ABBC: "s",    // PoW/PoS hybrid, 1/1.5 B premine
	ACT: "n",     // RDPOS?
	ADA: "n",
	ADK: "n",
	ADT: "n",
	ADX: "n",
	AE: "n",
	AGI: "n",
	AGRS: "n",
	AION: "n",
	AMP: "n",
	ANT: "n",
	AOA: "n",
	ARDR: "n",
	ARK: "n",
	AST: "n",
	ATB: "p",	 // ICO, mining will be available. Also uses PoS?? Looks like a hybrid?
	ATM: "n",
	ATOM: "n",	 // ICO
	B3: "n",     // Proof of stake
	BAT: "n",
	BAY: "n",    // Proof of stake
	BCC: "p",    // Ponzi Scam
	BCD: "m",
	BCH: "m",
	BCN: "s",    // 82% premined
	BCZERO: "n",
	BDL: "p",    // ICO, looks like a scam. http://archive.is/Cv46i
	BFT: "n",
	BIX: "n",
	BLOCK: "n",
	BNB: "n",
	BNT: "n",
	BOS: "n",
	BQ: "n",
	BQX: "n",
	BSV: "m",
	BTC: "m",
	BTCD: "p",   // 1.5% premined for bounties
	BTCP: "m", 
	BTG: "p",    // 100,000 BTG postmined https://archive.fo/xGa14
	BTM: "n",
	BTS: "n",
	BTT: "n",
	BTX: "p",
	BURST: "m",
	BXK: "n",
	CCCX: "n",
	CDT: "n",
	CENNZ: "n",
	CFI: "n",
	CLAM: "n",
	CLOAK: "n",
	CMT: "n",
	CND: "n",
	CNX: "n",    // Proof-of-stake
	COB: "n",
	CRO: "n",
	CTR: "n",
	CTXC: "n",
	CVC: "n",
	DAI: "n",
	DASH: "i",   // 2m DASH was mined in 48h
	DATA: "n",
	DCN: "n",
	DCR: "p",    // 8% premined
	DCT: "n",
	DDD: "n",
	DENT: "n",
	DEX: "n",
	DGB: "p",    // 100m premined
	DGD: "n",
	DGTX: "n",
	DICE: "n",
	DLT: "n",
	DNT: "n",
	DOGE: "m",
	DRGN: "n",
	DROP: "n",
	EB3: "s",    // Looks like a scam http://archive.is/7rjAz
	EDG: "n",
	EGT: "n",
	EKT: "n",
	ELA: "s",    // 33m in the genesis block
	ELF: "n",
	EMC: "m",
	EMC2: "m",
	ENG: "n",
	ENJ: "n",
	EOS: "n",
	ETC: "s",    // same as Ethereum
	ETH: "s",    // the genesis block contained 60.2m eth going to crowdsale participants + 11.9m split between early contributors and foundation,
	ETHOS: "n",
	ETN: "p",    // ICO
	ETP: "p",    // ICO
	EURS: "n",
	FAIR: "n",   // Switched from PoW to PoS
	FCT: "n",
	FRST: "s",   // 109.9m/110m premined? Looks like a scam
	FSN: "n",
	FTC: "i",    // instamined
	FUN: "n",
	FXC: "n",
	GAME: "m",
	GAS: "n",
	GBYTE: "n",
	GNO: "n",
	GNT: "n",
	GNX: "n",
	GRS: "p",    // 0.22918095% premined
	GTO: "n",
	GUSD: "n",
	GVT: "n",
	GXC: "n",
	HC: "s",
	HEDG: "n",
	HMQ: "n",
	HOT: "n",
	HSR: "n",
	HT: "n",
	ICN: "n",
	ICX: "n",
	ICO: "n",
	IGNIS: "n",
	INB: "n",
	INO: "n",
	IOC: "n",
	ION: "n",
	IOST: "n",
	JCT: "n",
	JINN: "n",
	KBC: "n",
	KCS: "n",
	KICK: "n",
	KIN: "n",
	KMD: "s",    // Initial supply of 100m for ICO and devs
	KNC: "n",
	LA: "n",
	LAMB: "n",
	LBC: "p",
	LINK: "n",
	LEO: "p",    // 50m premined
	LKK: "n",
	LKY: "n",
	LOOM: "n",
	LRC: "n",
	LSK: "n",
	LTC: "m",
	LUN: "n",
	MAID: "n",
	MANA: "n",
	MCAP: "n",
	MCO: "n",
	MDA: "n",
	MED: "n",
	MGO: "n",
	MIOTA: "n",
	MITH: "n",
	MKR: "n",
	MLN: "n",
	MNX: "p",     // ICO 5.5m premined
	MOAC: "n",
	MONA: "m",
	MTC: "n",
	MTH: "n",
	MTL: "n",
	MXM: "n",
	MYST: "n",
	NANO: "n",
	NAS: "n",
	NAV: "n",
	NCASH: "n",
	NEBL: "n",
	NEO: "n",
	NET: "n",
	NEX: "n",
	NEXO: "n",
	NLC2: "n",
	NLG: "p",     // 170m premined
	NMC: "m",
	NMR: "n",
	NPXS: "n",
	NRG: "n",     // transisitioned to PoS
	NULS: "n", 
	NXS: "m",
	NXT: "n",
	OAX: "n",
	ODE: "n",
	OK: "n",
	OMG: "n",
	ONT: "n",
	OTN: "n",
	PAC: "n",	  // Website is full of dead links
	PAI: "s",
	PART: "n",
	PAX: "n",
	PAY: "n",
	PIVX: "n",
	PLC: "n",
	PLR: "n",
	POE: "n",
	POLY: "n",
	POT: "n",     // Proof of stake now, originally started as PoW with Scrypt
	POWR: "n",
	PPC: "m",
	PPP: "n",
	PPT: "n",
	PPY: "n",
	PTOY: "n",
	PURA: "p",
	QASH: "n",
	QBIT: "n",
	QKC: "n",
	QNT: "n",
	QRL: "n",
	QSP: "n",
	QTUM: "n",
	R: "n",
	RBY: "n",
	RCN: "n",
	RDD: "n",
	RDN: "n",
	REC: "n",
	REN: "n",
	REP: "n",
	REPO: "n",
	REQ: "n",
	RHOC: "n",
	RIF: "n",
	RISE: "n",
	RLC: "n",
	ROUND: "n",
	RVN: "m",
	SAFEX: "n",
	S4F: "n",
	SALT: "n",
	SAN: "n",
	SC: "m",
	SKY: "n",
	SLV: "n",
	SMART: "m",    // this is ridiculous: https://explorer.smartcash.cc/richlist
	SNGLS: "n",
	SNM: "n",
	SNT: "n",
	SOC: "n",
	SPRTS: "p",    // mixed pow/pos
	SRN: "n",
	STEEM: "m",
	STORJ: "n",
	STORM: "n",
	STRAT: "n",
	STX: "n",
	SUB: "n",
	SYS: "p",     // 18% premined
	TAAS: "n",
	THETA: "n",
	THR: "n",
	TKN: "n",
	TNB: "n",
	TNT: "n",
	TRIG: "n",
	TRUE: "n",
	TRX: "n",
	TTC: "n",
	TTU: "n",
	TUSD: "n",
	UBQ: "m",
	UCASH: "n",
	USDC: "n",
	USDT: "n",
	UUU: "n",
	VEE: "n",
	VEN: "n",
	VERI: "n",
	VEST: "n",
	VET: "n",
	VIA: "p",     // ICO
	VSL: "n",
	VSYS: "n",
	VTC: "m",
	WAN: "n",      // Only mineable by WAN team, transitioning to PoS.
	WAVES: "n",
	WAX: "n",
	WICC: "n",
	WINGS: "n",
	WTC: "n",
	XAS: "p",     // ICO
	XBY: "n",	  // ICO
	XCP: "n",
	XDN: "m",
	XEL: "n",
	XEM: "n",
	XET: "n",
	XIN: "n",
	XLM: "n",
	XMR: "m",
	XMX: "n",
	XP: "n",      // Proof of Stake
	XPA: "n",
	XRL: "n",
	XRP: "n",
	XTZ: "n",
	XUC: "n",
	XVG: "m",
	XZC: "m",
	ZCL: "m",
	ZEC: "m",
	ZEN: "m",
	ZIL: "n",
	ZRX: "n",
	ZSC: "n"
}

mineable["1ST"] = "n";
